services:
  java-back:
    build:
      context: .
      dockerfile: /backend/DockerFile
    networks:
      - back-tier
    volumes:
      - data:/app/data
    restart: always
  nginx-front:
    build:
      context: .
      dockerfile: /frontend/DockerFile
    depends_on:
      - java-back
    restart: always
    networks:
      - back-tier
volumes:
  data:
networks:
  back-tier:
    driver: bridge
