services:
  java-back:
    build:
      context: ./backend  
      dockerfile: DockerFile  
    networks:
      - back-tier
    volumes:
      - data:/app/data
    restart: always

  nginx-front:
    build:
      context: ./frontend 
      dockerfile: DockerFile
    depends_on:
      - java-back
    restart: always
    networks:
      - back-tier

volumes:
  data:
networks:
  back-tier:
    driver: bridge
